import{a as p,S as m,i as l}from"./assets/vendor-64b55ca9.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();async function c(i,e){const o="42321228-2dc7965d40466a0a646776a28",r="https://pixabay.com"+"/api/",a={key:o,q:i,image_type:"photo",orientation:"horizontal",per_page:15,page:e};return(await p.get(r,{params:a})).data}let d;const s={formElem:document.querySelector(".form"),input:document.querySelector(".input-search"),button:document.querySelector(".button"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),buttonLoader:document.querySelector(".btn-more")};function f(i){return i.map(e=>`
        <li class="gallery-item"><a href="${e.largeImageURL}">
            <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}"></a>
            <div class="info">
            <p> <span class="info-text">Likes</span> <br/> ${e.likes}</p>
            <p><span class="info-text">Views</span> <br/> ${e.views}</p>
            <p><span class="info-text">Comments</span> <br/> ${e.comments}</p>
            <p><span class="info-text">Downloads</span> <br/> ${e.downloads}</p>
            </div>
            </li>
        `).join()}function h(i){const e=f(i);s.gallery.insertAdjacentHTML("beforeend",e),typeof LightBox<"u"?d.refresh():d=new m(".gallery a",{captionsData:"alt",captionDelay:250})}class g{constructor(){this.userInput="",this.page=1,this.maxPage=void 0}async onFormSubmit(e){if(e.preventDefault(),this.clearGallery(),this.page=1,this.userInput=s.input.value.trim(),this.userInput===""){l.error({message:"Please enter a search query.",position:"topRight",transitionIn:"fadeInLeft"});return}s.gallery.innerHTML="",this.showLoader(),this.hideLoadBtn();try{const o=await c(this.userInput,this.page);this.maxPage=Math.ceil(o.totalHits/15),o.hits.length===0?(this.hideLoader(),l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",transitionIn:"fadeInLeft"})):h(o.hits)}catch(o){l.error({message:o.message||"An error occurred. Please try again later.",position:"topRight",transitionIn:"fadeInLeft"})}this.hideLoader(),this.checkBtnStatus(),e.target.reset()}async loadMore(){this.page+=1,this.showLoader();const e=await c(this.userInput,this.page);h(e.hits),this.hideLoader();const o=s.gallery.firstElementChild;if(o){const n=o.getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}}showLoadBtn(){s.buttonLoader.classList.remove("hidden")}hideLoadBtn(){s.buttonLoader.classList.add("hidden")}showLoader(){s.loader.classList.remove("hidden")}hideLoader(){s.loader.classList.add("hidden")}clearGallery(){s.gallery.innerHTML=""}checkBtnStatus(){this.page>=this.maxPage?(this.hideLoadBtn(),this.hideLoader(),l.show({message:"We're sorry, but you've reached the end of search results.",position:"topRight",color:"blue",transitionIn:"fadeInLeft"})):s.buttonLoader.classList.remove("hidden")}}const u=new g;s.formElem.addEventListener("submit",i=>u.onFormSubmit(i));s.buttonLoader.addEventListener("click",()=>u.loadMore());
//# sourceMappingURL=commonHelpers.js.map
